import Foundation

/// When a pasteboard change count means "something new was copied".
public enum ClipboardChangeCount {
    /// `read` is the count the read found, `queued` the latest count known when the read was queued,
    /// `latest` the latest known now (raised by the app's own writes meanwhile). A count lower than
    /// the queued one means the pasteboard server restarted, so it is adopted; otherwise it is new
    /// only when higher than the latest known. Returns the count to adopt, or nil.
    public static func adopt(read: Int, queued: Int, latest: Int) -> Int? {
        if read < queued { return read }
        return read > latest ? read : nil
    }
}

/// Admission for pasteboard reads: one read in flight at a time, a baseline after every start, a
/// deadline after which a late result is dropped (while the slot stays taken until the read really
/// returns), and generations so a stop and start can never let an old read record anything.
public struct ClipboardCaptureGate: Sendable {
    public static let interval: TimeInterval = 0.8
    public static let tolerance: TimeInterval = 0.25
    public static let deadline: TimeInterval = 5

    public struct Ticket: Sendable, Equatable {
        public let generation: Int
        /// The latest count known when queued; nil means this read only takes the baseline.
        public let known: Int?
        public let issued: Date
    }

    public enum Outcome: Equatable, Sendable {
        /// The first read after a start: the count is recorded, nothing is captured.
        case baseline
        /// Nothing new.
        case unchanged
        /// Something new was copied; capture it.
        case new
        /// The read belongs to an earlier start, or missed its deadline; dropped.
        case stale
    }

    public private(set) var latest: Int?
    public private(set) var inFlight = false
    public private(set) var generation = 0
    public private(set) var running = false

    public init() {}

    /// Starts watching: the next read only takes a baseline.
    public mutating func start() {
        guard !running else { return }
        running = true
        generation += 1
        latest = nil
    }

    public mutating func stop() {
        guard running else { return }
        running = false
        generation += 1
    }

    /// A timer tick: a ticket when a read may be queued, nil while stopped or while a read is out.
    public mutating func admit(now: Date) -> Ticket? {
        guard running, !inFlight else { return nil }
        inFlight = true
        return Ticket(generation: generation, known: latest, issued: now)
    }

    /// Whether the reader should read contents for a count it found (never for a baseline read, and
    /// not when the count matches the known one).
    public static func shouldRead(count: Int, ticket: Ticket) -> Bool {
        guard let known = ticket.known else { return false }
        return count != known
    }

    /// The read returned. Always frees the slot.
    public mutating func complete(_ ticket: Ticket, count: Int, now: Date) -> Outcome {
        inFlight = false
        guard running, ticket.generation == generation, now.timeIntervalSince(ticket.issued) <= Self.deadline else { return .stale }
        guard let known = ticket.known, let current = latest else {
            latest = count
            return .baseline
        }
        guard let adopted = ClipboardChangeCount.adopt(read: count, queued: known, latest: current) else { return .unchanged }
        latest = adopted
        return .new
    }

    /// The app wrote to the pasteboard itself: raise the latest known count to the count the write
    /// produced, so its own writes are never recorded.
    public mutating func noteOwnWrite(count: Int) {
        latest = max(latest ?? count, count)
    }
}

/// What the history refuses to keep.
public enum ClipboardPrivacy {
    /// Marked by password managers and other apps as not for history (nspasteboard.org).
    public static let concealedType = "org.nspasteboard.ConcealedType"
    public static let transientType = "org.nspasteboard.TransientType"
    public static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"
    public static let skippedTypes: Set<String> = [concealedType, transientType, autoGeneratedType]

    /// A copy carrying any of the markers is not read at all.
    public static func skips(types: [String]) -> Bool {
        types.contains { skippedTypes.contains($0) }
    }

    static let sensitiveWords = ["password", "passwd", "secret", "token", "apikey", "api_key", "authorization"]

    /// Text that looks like a credential: it names one, or it is a 20–160-character string with no
    /// spaces that mixes a letter, a digit and a symbol. Web addresses and canonical UUIDs are fine,
    /// unless they name a credential.
    public static func looksSensitive(_ text: String) -> Bool {
        let lower = text.lowercased()
        if sensitiveWords.contains(where: { lower.contains($0) }) { return true }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard (20...160).contains(trimmed.count), !trimmed.contains(where: \.isWhitespace) else { return false }
        if isWebURL(trimmed) || isUUID(trimmed) { return false }
        var letter = false, digit = false, symbol = false
        for character in trimmed {
            if character.isLetter { letter = true } else if character.isNumber { digit = true } else { symbol = true }
        }
        return letter && digit && symbol
    }

    public static func isWebURL(_ text: String) -> Bool {
        let lower = text.lowercased()
        guard lower.hasPrefix("http://") || lower.hasPrefix("https://"),
              let url = URL(string: text, encodingInvalidCharacters: false) else { return false }
        return url.host?.isEmpty == false
    }

    /// 8-4-4-4-12 hexadecimal digits, either case, optionally in braces.
    public static func isUUID(_ text: String) -> Bool {
        var body = Substring(text)
        if body.hasPrefix("{") && body.hasSuffix("}") { body = body.dropFirst().dropLast() }
        let groups = body.split(separator: "-", omittingEmptySubsequences: false)
        guard groups.map(\.count) == [8, 4, 4, 4, 12] else { return false }
        return groups.allSatisfy { $0.allSatisfy(\.isHexDigit) }
    }

    /// A change is dropped when any app that was frontmost since the last read is on the skip list.
    public static func skips(frontmost: Set<String>, ignored: Set<String>) -> Bool {
        !frontmost.isDisjoint(with: ignored)
    }
}

/// Turning a copied string into what the history keeps.
public enum ClipboardText {
    public static let maximumLength = 1_000_000

    /// The text to keep, or nil: blank text and text over a million characters are not kept. A web
    /// address is kept as its absolute string; a scheme-relative or scheme-stripped copy whose
    /// pasteboard also carries the web URL gets the full URL back. Other text is kept exactly as copied.
    public static func normalize(_ string: String, webURL: String?) -> String? {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, string.utf16.count <= maximumLength * 2, trimmed.count <= maximumLength else { return nil }
        if ClipboardPrivacy.isWebURL(trimmed), let url = URL(string: trimmed, encodingInvalidCharacters: false) { return url.absoluteString }
        if let webURL, ClipboardPrivacy.isWebURL(webURL), let full = URL(string: webURL, encodingInvalidCharacters: false) {
            let stripped = full.absoluteString.replacingOccurrences(of: "^https?:", with: "", options: .regularExpression)
            let bare = stripped.hasPrefix("//") ? String(stripped.dropFirst(2)) : stripped
            if trimmed == stripped || trimmed == bare { return full.absoluteString }
        }
        return string
    }
}

/// A colour written as text (#RGB, #RRGGBB, #RRGGBBAA, rgb(), rgba()), for the card's swatch.
public struct ClipboardColor: Equatable, Sendable {
    public var red: Double, green: Double, blue: Double, alpha: Double

    public init(red: Double, green: Double, blue: Double, alpha: Double = 1) {
        self.red = red; self.green = green; self.blue = blue; self.alpha = alpha
    }

    /// The colour when the whole text is one colour value, else nil.
    public static func parse(_ text: String) -> ClipboardColor? {
        let value = text.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard value.count <= 40 else { return nil }
        if value.hasPrefix("#") { return hex(String(value.dropFirst())) }
        for prefix in ["rgba(", "rgb("] where value.hasPrefix(prefix) && value.hasSuffix(")") {
            let parts = value.dropFirst(prefix.count).dropLast().split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
            guard parts.count == 3 || parts.count == 4 else { return nil }
            let channels = parts.prefix(3).compactMap { Double($0) }
            guard channels.count == 3, channels.allSatisfy({ (0...255).contains($0) }) else { return nil }
            var alpha = 1.0
            if parts.count == 4 {
                guard let parsed = Double(parts[3]), (0...1).contains(parsed) else { return nil }
                alpha = parsed
            }
            return ClipboardColor(red: channels[0] / 255, green: channels[1] / 255, blue: channels[2] / 255, alpha: alpha)
        }
        return nil
    }

    private static func hex(_ digits: String) -> ClipboardColor? {
        guard [3, 6, 8].contains(digits.count), digits.allSatisfy(\.isHexDigit) else { return nil }
        let expanded = digits.count == 3 ? digits.map { "\($0)\($0)" }.joined() : digits
        guard let value = UInt64(expanded, radix: 16) else { return nil }
        let hasAlpha = expanded.count == 8
        let rgb = hasAlpha ? value >> 8 : value
        return ClipboardColor(red: Double((rgb >> 16) & 0xFF) / 255, green: Double((rgb >> 8) & 0xFF) / 255,
                              blue: Double(rgb & 0xFF) / 255, alpha: hasAlpha ? Double(value & 0xFF) / 255 : 1)
    }
}
