#!/usr/bin/env python3
"""Writes native/Sources/AgentProtocol/AgentExamples.swift from examples/sprites/.

Each examples/sprites/<name>.json becomes one example named <name>, its spec text kept exactly as written, with
the one-line summary from the table in examples/sprites/README.md (a spec has no key for it: an unknown key would
be a compiler warning in an example agents copy). The examples are compiled into the menusprite command so an
agent with only the MCP server can read them (list_examples, get_example). ExampleSpecsTests fails when the
generated file and the folder disagree, so run this after changing an example:

    python3 scripts/embed-agent-examples.py
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FOLDER = ROOT / "examples" / "sprites"
OUTPUT = ROOT / "native" / "Sources" / "AgentProtocol" / "AgentExamples.swift"
ROW = re.compile(r"^\|\s*`([A-Za-z0-9._-]+)`\s*\|\s*(.+?)\s*\|\s*$")


def summaries():
    found = {}
    for line in (FOLDER / "README.md").read_text(encoding="utf-8").splitlines():
        match = ROW.match(line)
        if match:
            found[match.group(1)] = match.group(2)
    return found


def raw_literal(text, indent):
    """A Swift multi-line raw string holding `text` exactly: enough #s that nothing in it closes or escapes."""
    hashes = "#"
    while '"""' + hashes in text or "\\" + hashes in text:
        hashes += "#"
    lines = "\n".join(indent + line if line else "" for line in text.split("\n"))
    return '%s"""\n%s\n%s"""%s' % (hashes, lines, indent, hashes)


def swift_string(text):
    return json.dumps(text, ensure_ascii=False).replace("\\/", "/")


def main():
    known = summaries()
    examples = []
    for path in sorted(FOLDER.glob("*.json")):
        name = path.stem
        text = path.read_text(encoding="utf-8")
        json.loads(text)  # a broken example fails here, not in an agent's hands
        if name not in known:
            sys.exit("examples/sprites/README.md has no summary row for `%s`." % name)
        if "\r" in text:
            sys.exit("%s has carriage returns; save it with plain newlines." % path.name)
        examples.append((name, known[name], text.rstrip("\n")))
    for name in sorted(set(known) - {name for name, _, _ in examples}):
        sys.exit("examples/sprites/README.md lists `%s`, which has no %s.json." % (name, name))

    entries = ",\n".join("        Example(name: %s, summary: %s,\n                json: %s)"
                         % (swift_string(name), swift_string(summary), raw_literal(text, " " * 16))
                         for name, summary, text in examples)
    swift = """// Generated by scripts/embed-agent-examples.py from examples/sprites/. Do not edit: change the example and run it again.

/// The example sprites in `examples/sprites/`, compiled in so an agent with only the MCP server (no checkout)
/// can read them: `list_examples` / `get_example`, the `menusprite://examples/<name>` resources, and
/// `menusprite examples [name]`. `ExampleSpecsTests` checks it matches the folder and that every example compiles
/// without a diagnostic.
public enum AgentExamples {
    public struct Example: Sendable {
        public let name: String
        public let summary: String
        /// The spec exactly as the file holds it (without its final newline).
        public let json: String
        public init(name: String, summary: String, json: String) { self.name = name; self.summary = summary; self.json = json }
    }
    public static let all: [Example] = [
%s
    ]
    public static func named(_ name: String) -> Example? { all.first { $0.name.caseInsensitiveCompare(name) == .orderedSame } }
}
""" % entries
    OUTPUT.write_text(swift, encoding="utf-8")
    print("Wrote %s: %d examples." % (OUTPUT.relative_to(ROOT), len(examples)))


if __name__ == "__main__":
    main()
