public enum PermissionCatalog {
    public static let all: [Permission] = [
        .init(.accessibility, "Accessibility", "accessibility", "Screen and input",
              "Control app interfaces and perform actions on your Mac.",
              explanation: "No control tools are active. The trust check reports effective access for this process. A false result cannot distinguish a first request from a previous denial. macOS may require a relaunch after a change.",
              anchor: "Privacy_Accessibility", requestable: true),
        .init(.inputMonitoring, "Input Monitoring", "keyboard", "Screen and input",
              "Observe keyboard, mouse and trackpad input outside the app.",
              explanation: "No input events are observed. Preflight only checks listening access; it cannot distinguish never requested from denied. Relaunch MenuSprite if macOS asks after a change.",
              anchor: "Privacy_ListenEvent", requestable: true),
        .init(.screenRecording, "Screen & System Audio Recording", "rectangle.inset.filled.and.person.filled", "Screen and input",
              "Allow screen recording; audio-only access is listed separately below.",
              explanation: "This row checks the screen-capture mode only. It does not establish the independent audio-only grant, persistent content selection or capture availability. Request Access starts consent without taking a screenshot or starting a stream. A relaunch may be required after changes.",
              anchor: "Privacy_ScreenCapture", requestable: true),
        .init(.systemAudio, "System audio only", "waveform", "Screen and input",
              "Record audio from other apps without recording the screen.",
              explanation: "A separate mode under Screen & System Audio Recording. There is no public, general audio-only preflight used by this build. No audio tap or recording is created to discover permission.",
              anchor: "Privacy_ScreenCapture", settingsName: "Screen & System Audio Recording → System Audio Recording Only"),
        .init(.remoteDesktop, "Remote Desktop", "desktopcomputer", "Screen and input",
              "Access screen and audio through remote desktop services.",
              explanation: "No remote desktop feature is installed. This category has no public general status/request adapter in MenuSprite; review its system entry if present.", settingsName: "Remote Desktop"),
        .init(.camera, "Camera", "camera", "Camera and audio",
              "Use a camera for photos or video.",
              explanation: "The authorization status is separate from camera hardware availability. Request Access asks macOS for consent only; no camera session starts. When revoking access, macOS can keep the current process authorized until it quits. Use Quit & Reopen when System Settings asks.",
              anchor: "Privacy_Camera", requestable: true),
        .init(.microphone, "Microphone", "mic", "Camera and audio",
              "Use a microphone to record sound.",
              explanation: "Request Access asks macOS for consent only. No audio input, recording or speech task starts. macOS may keep the current process authorized until it quits after revocation; use Quit & Reopen when asked.",
              anchor: "Privacy_Microphone", requestable: true),
        .init(.speech, "Speech Recognition", "waveform.and.mic", "Camera and audio",
              "Convert speech into text using Apple's speech service.",
              explanation: "Speech authorization and microphone authorization are separate. No recognizer, audio buffer or transcription task is created.",
              anchor: "Privacy_SpeechRecognition", requestable: true),
        .init(.filesAndFolders, "Files & Folders", "folder", "Files and applications",
              "Access protected folders and attached or network volumes.",
              explanation: "macOS exposes no universal status query for these resource grants. No folder is read or enumerated to probe them. A future file feature will request only the actual resource it needs.",
              anchor: "Privacy_FilesAndFolders"),
        .init(.fullDiskAccess, "Full Disk Access", "internaldrive", "Files and applications",
              "Access protected app data and other restricted files.",
              explanation: "Apple provides no official API confirming this grant. MenuSprite does not inspect TCC databases or test private files. A successful file read would not prove a universal grant. Relaunch if System Settings requests it.",
              anchor: "Privacy_AllFiles"),
        .init(.automation, "Automation", "applescript", "Files and applications",
              "Send Apple events to a specific application.",
              explanation: "Access belongs to each target app and event type. No targets are configured in this foundation, so no Apple events or permission probes are sent. A Finder grant would not authorize any other app.",
              anchor: "Privacy_Automation"),
        .init(.appManagement, "App Management", "app.badge", "Files and applications",
              "Update or remove other applications.",
              explanation: "No app-management feature is active. No app is modified as a permission probe; there is no public general preflight used by this build.",
              anchor: "Privacy_AppBundles"),
        .init(.developerTools, "Developer Tools", "hammer", "Files and applications",
              "Run software otherwise subject to additional system security checks.",
              explanation: "This is MenuSprite's potential Developer Tools access, not Xcode's or Terminal's. No general public status adapter is used; no executable is run to probe it.",
              anchor: "Privacy_DevTools"),
        .init(.contacts, "Contacts", "person.crop.rectangle", "Personal data",
              "Access names and other information in Contacts.",
              explanation: "Limited and system-restricted access are preserved. Request Access asks for consent; no contacts are fetched or changed.",
              anchor: "Privacy_Contacts", requestable: true),
        .init(.calendars, "Calendars", "calendar", "Personal data",
              "Read or add calendar events, according to the granted access level.",
              explanation: "Full access and write-only access are distinct. The optional request asks for full calendar access without fetching or writing any event.",
              anchor: "Privacy_Calendars", requestable: true),
        .init(.reminders, "Reminders", "checklist", "Personal data",
              "Read and manage reminders.",
              explanation: "The optional request asks for full reminder access. No reminder list or item is read or changed.",
              anchor: "Privacy_Reminders", requestable: true),
        .init(.photos, "Photos", "photo", "Personal data",
              "Access the photo library, with the level macOS allows.",
              explanation: "Read/write and add-only authorization are checked separately. Limited access is not full access. The optional request asks for read/write consent without loading photos.",
              anchor: "Privacy_Photos", requestable: true),
        .init(.music, "Media & Apple Music", "music.note", "Personal data",
              "Access Apple Music activity and media-library information.",
              explanation: "MusicKit reports authorization only. Playback, library queries and account requests are not started. An actual music integration and its signing capabilities are needed before offering a request.",
              anchor: "Privacy_Media"),
        .init(.homeKit, "HomeKit", "house", "Personal data",
              "Access home and accessory information.",
              explanation: "HomeKit's app framework is not available to this native macOS target. A settings category can exist for other app types without being usable by MenuSprite.",
              anchor: "Privacy_HomeKit"),
        .init(.focus, "Focus", "moon", "Personal data",
              "Know whether notifications are silenced by a Focus.",
              explanation: "Only authorization is checked, not your current Focus status. No communication or Focus integration is configured, so there is no request action.",
              anchor: "Privacy_Focus"),
        .init(.motion, "Motion & Fitness", "figure.walk", "Personal data",
              "Access motion and fitness activity information.",
              explanation: "CMMotionActivityManager is unavailable to native macOS apps in the selected SDK. No motion or fitness data is queried.",
              anchor: "Privacy_Motion"),
        .init(.bluetooth, "Bluetooth", "antenna.radiowaves.left.and.right", "Network and location",
              "Find and communicate with Bluetooth accessories.",
              explanation: "Only the static CoreBluetooth authorization value is read. No Bluetooth manager is created and no scan or connection starts. Authorization is separate from radio power or device availability.",
              anchor: "Privacy_Bluetooth"),
        .init(.localNetwork, "Local Network", "network", "Network and location",
              "Find and communicate with devices on your network.",
              explanation: "No general preflight is available here. Offline state and failed connections do not prove denial. MenuSprite does not send packets or start discovery to probe this grant.",
              anchor: "Privacy_LocalNetwork"),
        .init(.location, "Location Services", "location", "Network and location",
              "Use the Mac's location for location-aware features.",
              explanation: "Global Location Services and MenuSprite's authorization are shown separately. The request asks for when-in-use authorization only; no location updates or coordinates are requested.",
              anchor: "Privacy_LocationServices", requestable: true),
        .init(.passkeys, "Passkeys Access for Web Browsers", "person.badge.key", "Browser credentials",
              "Let a browser use saved passkeys to sign in to websites.",
              explanation: "MenuSprite is not a web browser and has no browser passkey capability. The special browser entitlement and an implemented browser integration would be required; no credential query is made.",
              settingsName: "Passkeys Access for Web Browsers"),
        .init(.notifications, "Notifications", "bell", "Alerts",
              "Show alerts, sounds and badges.",
              explanation: "Authorization does not guarantee delivery. Alert, sound, badge and Notification Center settings appear below. Request Access asks for consent only; no notification is scheduled or sent.",
              requestable: true),
        .init(.pasteboard, "Clipboard", "doc.on.clipboard", "Clipboard",
              "Control programmatic access to the general pasteboard.",
              explanation: "The API reports access behavior, not a blanket clipboard grant. User-initiated paste can still be allowed under Always deny. No clipboard content, item count or change count is read. There is no request button because probing would read content.",
              settingsName: "Paste from Other Apps"),
        .init(.health, "Health data", "heart", "Additional framework access",
              "Read or share individual types of health data where supported.",
              explanation: "HealthKit availability is checked before any authorization use. No health types are configured. Read authorization is intentionally undisclosed; share/write permission would be per type. No health store queries are made.", hasSettings: false),
        .init(.tracking, "App Tracking Transparency", "hand.raised", "Additional framework access",
              "Ask to track activity across other companies' apps and websites.",
              explanation: "MenuSprite does not track you. Apple's native macOS API always returns notDetermined, so that value is not treated as meaningful pending consent. No tracking request or identifier lookup is implemented.", hasSettings: false),
        .init(.login, "Launch at login", "power", "App services and other access",
              "Start MenuSprite in the menu bar when you sign in.",
              explanation: "This is a service registration, not a privacy grant. Enable or disable changes only MenuSprite's main-app login registration, then rereads macOS's result. The settings page stays closed at login.",
              hasSettings: false, usedBy: "MenuSprite startup", isOtherAccess: true),
        .init(.backgroundHelpers, "Background helpers", "gearshape.2", "App services and other access",
              "Run specifically registered MenuSprite helper services.",
              explanation: helperExplanation,
              hasSettings: false, usedBy: powerHelperUse, isOtherAccess: true),
        .init(.administrator, "Administrator-authorized operations", "lock.shield", "App services and other access",
              "Approve a specific privileged helper or operation.",
              explanation: adminExplanation,
              hasSettings: false, usedBy: powerHelperUse, isOtherAccess: true),
        .init(.selectedFiles, "Selected files & retained access", "folder.badge.plus", "App services and other access",
              "Keep access to resources you explicitly select.",
              explanation: "No file selections or security-scoped bookmarks are stored. Future entries must identify each resource and whether its retained access still works. Removing a local reference does not revoke system-wide permission.",
              hasSettings: false, isOtherAccess: true),
        .init(.keychain, "Keychain & credentials", "key", "App services and other access",
              "Store and use credentials for named integrations.",
              explanation: "No credential integrations or stored secret references exist. The page does not enumerate Keychain or claim a blanket Keychain grant.",
              hasSettings: false, isOtherAccess: true),
        .init(.extensions, "Extensions & network configurations", "puzzlepiece.extension", "App services and other access",
              "Activate a concrete extension or managed network service.",
              explanation: "No system extension, network extension, VPN or filter is bundled or configured. Activation state will belong to the specific service if one is added.",
              hasSettings: false, isOtherAccess: true),
        .init(.hardware, "Hardware control", "fan", "App services and other access",
              "Use a dedicated helper for supported fan or charge controls.",
              explanation: hardwareExplanation,
              hasSettings: false, usedBy: powerHelperUse, isOtherAccess: true)
    ]

    #if MENUSPRITE_PUBLIC_PREVIEW
    private static let powerHelperUse = "Not used by MenuSprite"
    private static let helperExplanation = "No privileged helper is bundled with this public preview. Monitoring and ordinary keep-awake run without one."
    private static let adminExplanation = "This public preview performs no administrator-authorized operations. macOS has no permanent global Administrator grant for an app."
    private static let hardwareExplanation = "Hardware controls are excluded from this public preview. Fan, temperature and power readings are read-only and are not generic privacy grants."
    #else
    private static let powerHelperUse = "Battery and closed-lid controls (optional)"
    private static let helperExplanation = "The signed MenuSprite power helper is bundled for battery and closed-lid controls. Installation is separate from feature activation; Power Controls verifies its live connection."
    private static let adminExplanation = "Installing or removing the dedicated power helper needs administrator authorization. macOS has no permanent global Administrator grant for this app."
    private static let hardwareExplanation = "The power helper implements supported charge and adapter controls. Capability is checked on Power Controls and remains separate from activation. No fan control is implemented. These are not generic macOS privacy grants."
    #endif

    public static var groups: [String] {
        all.reduce(into: []) { if !$0.contains($1.group) { $0.append($1.group) } }
    }
}
